feat: using -DDCM_ENABLED in debian/rules to enable compatible mode
deepin-community/glibc pull request #19
Opened 2024-10-12 09:05 UTC by errorcode7

add search lib from subsystem ,and inhibit RUNPATH and LIBRARY,
    make sure library load order: host > subsystem > elf specified dir .

    using subsystem by env:
        ROOTFS=/lib/var/rootfs/debian10
        export DCM_LIBRARY_PATH="$ROOTFS/lib:$ROOTFS/lib/x86_64-linux-gnu"

    extra control env：
        DCM_ORIGIN_LIBRARY_MODE=LAZY
        DCM_RUNPATH_MODE=LAZY/IGNORE
        DCM_SYSPATH_MODE=IGNORE

Description: add library redirection compatible mode

Log: add library redirection compatible mode

2024-10-12 09:17 UTC, Zeno-sole commented
/ok-to-test

2024-10-12 09:31 UTC, liujianqiang-niu approved these changes

2024-10-12 10:06 UTC, black-desk requested changes

2024-10-12 10:06 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++  if (llp != NULL && *llp != '\0')
考虑early return

2024-10-12 10:06 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++      char *llp_tmp = strdupa (llp);
对应的free呢

2024-10-12 10:06 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++      for (const char *cp = llp_tmp; *cp != '\0'; ++cp)
要不要考虑一下限制llp的最大长度以免误传入了一个别的什么指针然后段错误。

2024-10-12 10:06 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++	  ++nllp;
你这样写的话如果llp的内容是一个空格之类的，是不是依然会被认为有一个元素。

之前有没有别的检查

2024-10-12 10:06 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++      		if (__run_path_mode == 2) //2=normal;1=lazy;0=sikp
这个能不能正经用点宏或者enum之类的 注释感觉不是很能靠得住

2024-10-12 10:06 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++      		if (__run_path_mode == 2) //2=normal;1=lazy;0=sikp
以及这个if 以及接下来的一串if的缩进不对

2024-10-12 10:06 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++    int mode;
这个确定一下有没有影响abi。

2024-10-12 10:19 UTC, black-desk requested changes

2024-10-12 10:19 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++   if(state->run_path_mode !=NULL && memcmp(state->run_path_mode,"LAZY",4) == 0)
用sizeof吧 这个地方用4不对，如果非要写常量也应该是5 4的话 你会认为LAZYA之类的东西也是LAZY

2024-10-12 10:19 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++    int mode;
以及这个是不是也应该用enmu或者宏

2024-10-12 10:19 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++      if ( __rtld_env_path_list.mode == 1 && fd == -1 && __rtld_env_path_list.dirs != (void *) -1)
这里应该防御一下 __rtld_env_path_list.dirs==NULL

2024-10-12 10:19 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++   if(state->run_path_mode !=NULL && memcmp(state->run_path_mode,"IGNORE",6) == 0)
同上

2024-10-12 10:19 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++   if(state->sys_path_mode !=NULL &&  memcmp(state->sys_path_mode,"IGNORE",6) == 0)
同上

2024-10-12 10:55 UTC, black-desk requested changes

2024-10-12 10:55 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++      if ( fd == -1 && __rtld_search_dirs.dirs !=NULL  && __run_path_mode == 1)
空格

2024-10-12 10:55 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++			fd = open_path (name, namelen, mode, &__rtld_subsys_path_list,
缩进

2024-10-14 01:28 UTC, Avenger-285714 commented on debian/patches/any/uniontech001-compat-mode.patch
> ++   if(state->run_path_mode !=NULL && memcmp(state->run_path_mode,"LAZY",4) == 0)
> 用sizeof吧 这个地方用4不对，如果非要写常量也应该是5 4的话 你会认为LAZYA之类的东西也是LAZY

兴许strcmp省事些（

2024-10-14 02:30 UTC, black-desk requested changes

2024-10-14 02:30 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++	  __rtld_subsys_path_list.dirs = (void *) -1;
这里最好不要用-1来表示这东西是空的，因为和这个东西类似的其他变量（比如下面也使用到的__rtld_search_dirs.dirs）明显是用NULL来表示其不存在的。
而且NULL是默认值。

2024-10-14 02:30 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++    __rtld_subsys_path_list.dirs = (void *) -1;
同上

2024-10-14 02:30 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++   __rtld_env_path_list.mode = 0;
一样的 这里改了用宏或者enum

2024-10-14 02:30 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++   __rtld_search_dirs.mode = 1;
同上

2024-10-14 02:30 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++   __run_path_mode = 2;
同上

2024-10-14 02:30 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++      __rtld_env_path_list.mode = 1;
同上

2024-10-14 02:30 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++      __run_path_mode = 1;
用enum

2024-10-14 02:30 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++//env control  __rtld_env_path_list.mode
注释多写一点

2024-10-14 02:30 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++  const char *subsystem_path_source;
这些新加的字段的内存的所有权是谁的 我没有看到你改对应的free流程 是真的不需要么

2024-10-14 02:30 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++      if (__builtin_expect ((*current)[0] == 'D', 0)
一样的early return

2024-10-14 02:30 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++      case 12:
虽然glibc里面的类似的地方也是这样直接用的字面常量，我们这里是不是可以考虑一下用sizeof

2024-10-14 02:30 UTC, black-desk commented on debian/patches/any/uniontech001-compat-mode.patch
> ++            && memcmp (envline, "ORIGIN_LIBRARY_MODE", 19) == 0)//ORIGIN_LIBRARY_MODE/19
这个注释是什么意思

2024-10-17 07:08 UTC, errorcode7 commented on debian/patches/any/uniontech001-compat-mode.patch
> ++            && memcmp (envline, "ORIGIN_LIBRARY_MODE", 19) == 0)//ORIGIN_LIBRARY_MODE/19
已经取消注释了。

2024-10-17 07:09 UTC, errorcode7 commented on debian/patches/any/uniontech001-compat-mode.patch
> ++      case 12:
保持风格一致吧

2024-10-17 07:10 UTC, errorcode7 commented on debian/patches/any/uniontech001-compat-mode.patch
> ++  const char *subsystem_path_source;
原来的代码里处理环境也没有free。对环境变量只有读取，没有修改。

2024-10-17 07:11 UTC, errorcode7 commented on debian/patches/any/uniontech001-compat-mode.patch
> ++   __rtld_env_path_list.mode = 0;
好建议

2024-10-17 07:12 UTC, errorcode7 commented on debian/patches/any/uniontech001-compat-mode.patch
> ++	  __rtld_subsys_path_list.dirs = (void *) -1;
确实是个问题，dirs指针，均从NULL改为 (void *) -1

2024-10-17 07:12 UTC, errorcode7 commented on debian/patches/any/uniontech001-compat-mode.patch
> ++			fd = open_path (name, namelen, mode, &__rtld_subsys_path_list,
已经处理

2024-11-29 07:36 UTC, closed without merging